[workspace]
members = [
    "e2e",
    "examples/counter",
    "examples/naming_system",
    "examples/fib",
    "ic-kit",
    "ic-kit-sys",
    "ic-kit-macros",
    "ic-kit-runtime",
]

[profile.canister-release]
inherits = "release"
debug = false
panic = "abort"
lto = true
opt-level = 'z'