[workspace]
members = [
    "examples/counter",
    "examples/naming_system",
    "examples/fib",
    "ic-kit",
    "ic-kit-sys",
    "ic-kit-macros",
    "ic-kit-runtime",
]

[profile.release]
lto = true
opt-level = 'z'

[patch.crates-io]
num-bigint = { git = "https://github.com/rust-num/num-bigint" }
