[package]
name = "ic-kit"
version = "0.4.8"
description = "Testable Canister Developer Kit for the Internet Computer."
authors = ["Parsa Ghadimi <parsa@fleek.co>", "Ossian Mapes <oz@fleek.co>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/Psychedelic/ic-kit"
homepage = "https://docs.rs/ic-kit"
documentation = "https://docs.rs/ic-kit"
categories = ["api-bindings", "data-structures", "development-tools::testing"]
keywords = ["internet-computer", "canister", "cdk", "fleek"]
include = ["src", "Cargo.toml", "README.md"]

[dependencies]
ic-kit-sys = {path="../ic-kit-sys", version="0.1.0"}
ic-kit-macros = {path="../ic-kit-macros", version="0.1.0"}
ic-kit-runtime = {path="../ic-kit-runtime", version="0.0.1"}
serde = "1.0"
wasm-rs-async-executor = "0.9.0"
tokio = {version="1.20", features=["sync", "macros"]}
ic-cdk = "0.5.5"
candid="0.7"

[patch.crates-io]
num-bigint = { git = "https://github.com/rust-num/num-bigint" }
